version: '3.8'

services:
  # Backend API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: local-dev
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - PORT=8080
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=45ai_dev
      - DB_USER=root
      - DB_PASSWORD=password123
      - JWT_SECRET=dev_jwt_secret_key_change_in_production
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - 45ai-network
    restart: unless-stopped

  # MySQL database
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=45ai_dev
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - 45ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
    driver: local

networks:
  45ai-network:
    driver: bridge